### PR TITLE
Added stochastic universal sampling selection method

### PR DESCRIPTION
**Pull request by enesates**
It is an implementation of the [Stochastic Universal Sampling](https://en.wikipedia.org/wiki/Stochastic_universal_sampling) selection technique.

### CODE REVIEW

**Comment by fmder** [comment]
Cannot this be done more simply with indexing?

`return individuals[start::distance]`

with `start` and `distance` being integers

**Comment by enesates** [comment]
I don't think so.

The algorithm uses a `distance` value is equal to `total_fitness/population_size` and an initial value `start` is between 0 and `distance`. Pointer list starts with `start` and continues `start + distance * i` and so on.

Then it uses pointer list's elements to choose parents. Higher fitness will be most likely to be chosen. The algorithm also gives weaker members of the population a chance to be chosen.

There is an example for the algorithm: [http://www.geatbx.com/docu/algindex-02.html](http://www.geatbx.com/docu/algindex-02.html).

You may have a better and simple solution. I also will think about it.

**Comment by fmder** [comment]
Sorry about that! I read the PR too quickly.

**Comment by enesates** [comment]
Thank you.

**Pull request merged**
