### PR TITLE
Fix and merge MetaCreator

### PR DESCRIPTION
**Pull request by fmder**
#76 Merged into current master.

fixes #76

### CODE REVIEW

**Comment by fmder** [comment]
@bje- I think I got everything working from #76. Could you test if Ray can work with this? I added automated tests, but it is not 100% coverage unfortunately.

**Comment by bje-** [comment]
> #76 Merged into current master.

I don't see a merge commit on master?

**Comment by bje-** [comment]
> I don't see a merge commit on master?

Ah, it's still on a branch.

**Comment by bje-** [comment]
No improvement that I can see:

```
(PoolActor pid=3240907) AttributeError: Can't get attribute 'Individual' on <module 'deap.creator' from '/home/bje/source/nemo/myenv/lib/python3.10/site-packages/deap/creator.py'> 
```

**Comment by fmder** [comment]
Was #76 fixing the issue before?

**Comment by bje-** [comment]
The changes don't merge so I wasn't easily able to test it.

**Comment by fmder** [comment]
You'd need the changes to be on master?

**Comment by bje-** [comment]
Still from the fmder-metacreator branch:
```
ray.exceptions.RaySystemError: System error: Can't get attribute 'Individual' on <module 'deap.creator' from '/home/bje/source/nemo/myenv/lib/python3.10/site-packages/deap/creator.py'>
```

**Comment by fmder** [comment]
Ok, i'll check later today if I can find something I missed while merging

**Comment by fmder** [comment]
Thanks for the feedback

**Comment by bje-** [comment]
"current version" being master?

**Comment by bje-** [comment]
**Follow-up**: I made the change below to `onemax_mp.py` and it works. I think the problem must be in my code.

```
diff --git a/examples/ga/onemax_mp.py b/examples/ga/onemax_mp.py
index 32d34e0..3377b5f 100755
--- a/examples/ga/onemax_mp.py
+++ b/examples/ga/onemax_mp.py
@@ -18,6 +18,7 @@ import array
 import multiprocessing
 import random
 import sys
+import ray.util.multiprocessing
 
 if sys.version_info < (2, 7):
     print("mpga_onemax example requires Python >= 2.7.")
@@ -54,7 +55,7 @@ def main(seed):
     toolbox.register("select", tools.selTournament, tournsize=3)
 
     # Process Pool of 4 workers
-    pool = multiprocessing.Pool(processes=4)
+    pool = ray.util.multiprocessing.Pool(processes=4)
     toolbox.register("map", pool.map)
 
     pop = toolbox.population(n=300)
```

**Pull request merged**
