### PR TITLE
Fix errors in the cxOrdered function

### PR DESCRIPTION
**Pull request by kamua**
Proposed error fixing is according to [Goldberg1989]. It was tested on the example in page 174 of [Goldberg1989]:

image

### CODE REVIEW

**Comment by fmder** [comment]
This crossover is as old as DEAP itself! Could you add a unit test that confirms the crossover's behaviors?

**Comment by kamua** [comment]
For testing two additional code lines were included into the copy of the original function (without docstrings):
1. The line `a, b = 3, 5` fixes values of the a and b parameters which determine the same matching section as in page 174 of the book [Goldberg1989].
2. The line `print(holes1, holes2)` is in order to compare holes found in the function with string B in the Goldberg's book.

```python
def cxOrdered(ind1, ind2):
    size = min(len(ind1), len(ind2))
    a, b = random.sample(xrange(size), 2)
    if a > b:
        a, b = b, a

    a, b = 3, 5 # kamua: This values determine the same matching section as in page 174 of the Goldberg's book.

    # kamua: this code block finds holes incorrectly
    holes1, holes2 = [True] * size, [True] * size
    for i in range(size):
        if i < a or i > b:
            holes1[ind2[i]] = False
            holes2[ind1[i]] = False

    print('    Holes:', holes1, holes2) # kamua: it's in order to compare holes found in the function with string B in the Goldberg's book.

    # We must keep the original values somewhere before scrambling everything
    temp1, temp2 = ind1, ind2
    k1, k2 = b + 1, b + 1
    for i in range(size):
        if not holes1[temp1[(i + b + 1) % size]]:
            ind1[k1 % size] = temp1[(i + b + 1) % size]
            k1 += 1

        if not holes2[temp2[(i + b + 1) % size]]:
            ind2[k2 % size] = temp2[(i + b + 1) % size]
            k2 += 1

    # Swap the content between a and b (included)
    for i in range(a, b + 1):
        ind1[i], ind2[i] = ind2[i], ind1[i]

    return ind1, ind2
```
Now we define two chromosomes from the example in page 174 of Goldberg's book and test the fucnction:
image
```python
indA = [9, 8, 4, 5, 6, 7, 1, 3, 2, 10]
indB = [8, 7, 1, 2, 3, 10, 9, 5, 4, 6]
print('  Parents:', indA, indB)
cxOrdered(indA, indB)
print('Offspring:', indA, indB)
```
```
  Parents: [9, 8, 4, 5, 6, 7, 1, 3, 2, 10] [8, 7, 1, 2, 3, 10, 9, 5, 4, 6]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-6259cc2899b0> in <module>()
      2 indB = [8, 7, 1, 2, 3, 10, 9, 5, 4, 6]
      3 print('  Parents:', indA, indB)
----> 4 cxOrdered(indA, indB)
      5 print('Offspring:', indA, indB)

<ipython-input-2-128a469538c8> in cxOrdered(ind1, ind2)
     30         if i < a or i > b:
     31             holes1[ind2[i]] = False
---> 32             holes2[ind1[i]] = False
     33 
     34     print('    Holes:', holes1, holes2) # kamua: it's in order to compare holes found in the function with string B in the Goldberg's book.

IndexError: list assignment index out of range
```
The function returns an error because it uses gene values as integer indexes in the range [0, n-1] where n is a chromosome length (this is an unnecessary restriction on possible gene values).

Let's rewrite the gene values into the range [0, n-1]:
```python
indA = [8, 7, 3, 4, 5, 6, 0, 2, 1, 9]
indB = [7, 6, 0, 1, 2, 9, 8, 4, 3, 5]
print('  Parents:', indA, indB)
cxOrdered(indA, indB)
print('Offspring:', indA, indB)
```
```
  Parents: [8, 7, 3, 4, 5, 6, 0, 2, 1, 9] [7, 6, 0, 1, 2, 9, 8, 4, 3, 5]
    Holes: [False, True, True, False, False, False, False, False, False, True] [False, False, False, False, True, True, True, False, False, False]
Offspring: [4, 5, 6, 1, 2, 9, 0, 8, 7, 3] [1, 2, 9, 4, 5, 6, 8, 3, 7, 0]
```
Now the function returns no errors but the hole positions are found incorrectly. From Goldberg's example:
image
I do not know why, but at the same time the function returns offspring correctly:
image
This may be a random coincidence.

I suggest to correct procedure of finding the holes and at the same time to eliminate the restrictions on the range of gene values:
```python
def cxOrdered_corrected(ind1, ind2):
    size = min(len(ind1), len(ind2))
    a, b = random.sample(xrange(size), 2)
    if a > b:
        a, b = b, a

    a, b = 3, 5 # kamua: This values determine the same matching section as in page 174 of the book [Goldberg1989].

    # holes1, holes2 = [True] * size, [True] * size # original line
    holes1, holes2 = [False] * size, [False] * size # kamua
    for i in range(size):
        if i < a or i > b:
            # holes1[ind2[i]] = False # original line
            # holes2[ind1[i]] = False # original line
            holes1[i] = ind1[i] in ind2[a : b + 1] # kamua
            holes2[i] = ind2[i] in ind1[a : b + 1] # kamua

    print('    Holes:', holes1, holes2) # kamua: it's in order to compare holes found in the function with string B in the Goldberg's book.

    # We must keep the original values somewhere before scrambling everything
    temp1, temp2 = ind1, ind2
    k1, k2 = b + 1, b + 1
    for i in range(size):
        # if not holes1[temp1[(i + b + 1) % size]]: # original line
        if not holes1[(i + b + 1) % size]: # kamua
            ind1[k1 % size] = temp1[(i + b + 1) % size]
            k1 += 1

        # if not holes2[temp2[(i + b + 1) % size]]: # original line
        if not holes2[(i + b + 1) % size]: # kamua
            ind2[k2 % size] = temp2[(i + b + 1) % size]
            k2 += 1

    # Swap the content between a and b (included)
    for i in range(a, b + 1):
        ind1[i], ind2[i] = ind2[i], ind1[i]

    return ind1, ind2
```
Now the function correctly finds the hole positions as well as returns offspring (independently of gene values):
image
image
```python
indA = [9, 8, 4, 5, 6, 7, 1, 3, 2, 10]
indB = [8, 7, 1, 2, 3, 10, 9, 5, 4, 6]
print('  Parents:', indA, indB)
cxOrdered_corrected(indA, indB)
print('Offspring:', indA, indB)
```
```
  Parents: [9, 8, 4, 5, 6, 7, 1, 3, 2, 10] [8, 7, 1, 2, 3, 10, 9, 5, 4, 6]
    Holes: [False, False, False, False, False, False, False, True, True, True] [False, True, False, False, False, False, False, True, False, True]
Offspring: [5, 6, 7, 2, 3, 10, 1, 9, 8, 4] [2, 3, 10, 5, 6, 7, 9, 4, 8, 1]
```
```python
indA = [8, 7, 3, 4, 5, 6, 0, 2, 1, 9]
indB = [7, 6, 0, 1, 2, 9, 8, 4, 3, 5]
print('  Parents:', indA, indB)
cxOrdered_corrected(indA, indB)
print('Offspring:', indA, indB)
```
```
  Parents: [8, 7, 3, 4, 5, 6, 0, 2, 1, 9] [7, 6, 0, 1, 2, 9, 8, 4, 3, 5]
    Holes: [False, False, False, False, False, False, False, True, True, True] [False, True, False, False, False, False, False, True, False, True]
Offspring: [4, 5, 6, 1, 2, 9, 0, 8, 7, 3] [1, 2, 9, 4, 5, 6, 8, 3, 7, 0]
```

**Comment by fmder** [comment]
Unfortunately, I tested your version and it does not return a valid permutation in all cases. For example,

```python
a = [3, 7, 2, 4, 6, 5, 8, 9, 1, 0]
b = [7, 2, 3, 6, 8, 4, 9, 0, 1, 5]

with mock.patch("random.sample", return_value=[3, 5]):
    ap, bp = cxOrdered_corrected(a, b)

ap = [7, 2, 4, 8, 4, 4, 9, 1, 0, 3]
bp = [2, 3, 6, 6, 5, 5, 9, 0, 1, 7]
```

Moreover, I remember changing the implementation from the naive holes that is O(n^2) in complexity to a O(n) implementation. Looking at this last example, if we follow Goldberg's paper

```python
a = [3, 7, 2, | 4, 6, 5, | 8, 9, 1, 0]
b = [7, 2, 3, | 6, 8, 4, | 9, 0, 1, 5]
```

Holes in ``a`` and ``b`` are

```python
holes1 = [3, 7, 2, | H, H, 5, | H, 9, 1, 0]
holes2 = [7, 2, 3, | H, 8, H, | 9, 0, 1, H]
```

after sliding

```python
holes1 = [7, 2, 5 | H, H, H, | 9,  1, 0, 3]
holes2 = [2, 3, 8 | H, H, H, | 9, 0, 1, 7]
```
Swap content of what was in the crossover points

```python
ap = [7, 2, 5 | 6, 8, 4, | 9, 1, 0, 3]
bp = [2, 3, 8 | 4, 6, 5, | 9, 0, 1, 7]
```

And that is the output of the current implementation.

**Comment by kamua** [comment]
You are right, my version of the function returns incorrect result. Sorry.

But I don't understand why your version of the function finds hole positions incorrectly (outside matching section) but returns correct offspring. It maybe due to performed optimization of time complexity.

**Comment by fmder** [comment]
The holes in my version represent not their true position but the value the should be a hole. This is why the algorithm works only for [0..N-1].

**Pull request closed without merging**
