### PR TITLE
Adapt selectors to use choosable attributes as criterion

### PR DESCRIPTION
**Pull request by cyrilpic**
The selection tools are very convenient tools, but they could be made a bit more general if one could say which attribute of an individual to choose from.

Possible use cases are IBEA or HypE algorithms where an indicator function is used as an additional "fitness". With this patch request, the available selection tools could also be used for such cases.

### CODE REVIEW

**Comment by cyrilpic** [comment]
Is there something I could/should change for you to accept this pull request? Thanks

**Comment by fmder** [comment]
I think it is a good idea and it is back compatible with DEAP. Although, it opens the possibility of bugs for users that might not be perceptible at first and mess with their results. I think you should add a tutorial on how to use this feature and most importantly what constitute a good attribute to select as ind_attr (that I would rename fit_attr).

And sorry for the delay,

**Comment by cyrilpic** [comment]
I updated the attribute's name and also fixed some typo bugs. The tests are passing and I also made manuel tests for most selection methods. I'd say that the risk of bugs has been reduced to a minimum.
As a "tutorial", I added an example script "mo_rhv" that shows an application of it.

**Comment by fmder** [comment]
I meant if someone enters an attribute name that will sort its population
but not with the desired effect because of type of this attribute. This is
the kind of bug I apprehend.

**Pull request merged**
