### PR TITLE
Walking Fish Group multi-objective problems

### PR DESCRIPTION
**Pull request by lmarti**
I have been working with @CesarRevelo on programming the WFG problems in Python. Here is the result. We have tested the module. You can check out these tests in https://github.com/lmarti/wfg-deap/.

### CODE REVIEW

**Comment by lmarti** [comment]
Hi, if you think that this PR is not suitable for you just let me know so we distribute it separately. Cheers :)

**Comment by CesarRevelo** [comment]
Hi lmarti, really I'm interesting in distribute this PR with you, I want to continue contributing to this project.

**Comment by fmder** [comment]
I'm sorry I really haven't had any spare time to review this PR. I'll have
a quick chat with Felix to have a consolidated answer and come back to you
with an answer as soon as possible.


Thanks for this PR,
Regards,
François-Michel

2015-08-20 13:08 GMT-04:00 Cesar David Revelo <notifications@github.com>:

**Comment by lmarti** [comment]
I am going to distribute this separately while you get ready for a PR.

**Pull request closed without merging**
