### PR TITLE
Add aarch64 wheel support

### PR DESCRIPTION
**Pull request by odidev**
Added aarch64 wheel support.
Related to #558. @fmder Please review the changes.

### CODE REVIEW

**Comment by odidev** [comment]
@fmder, could you please take a look at this PR? Thanks.

**Comment by odidev** [comment]
@timgates42, could you please take a look at this PR? Thanks.

**Comment by fmder** [comment]
Sorry, I’m not sure how to test that really 🤔

**Comment by fmder** [comment]
Do you have a aarch64 machine if I publish the wheels you can test?

**Comment by odidev** [comment]
> Do you have a aarch64 machine if I publish the wheels you can test?

Yes, that would be great. I have the machine. I will test the published wheel

**Comment by odidev** [comment]
@fmder, could you please let me know the plans for releasing AArch64 wheels on PyPi. Thanks.

**Comment by fmder** [comment]
I guess there is no better way to test this than run it and it looks like we got a success! @odidev you can try the package from PyPi. https://pypi.org/project/deap/#files

**Comment by sgmoratilla** [comment]
Hey @fmder! I know a lot of time has passed, but I wanted to check if you got any news from @odidev.

If you can point me how to test this, I can give it a try, so the aarch64 version can be published.

**Comment by fmder** [comment]
Some aarch64 wheels are already on pypi https://pypi.org/manage/project/deap/release/1.3.1/

**Comment by odidev** [comment]
> @odidev you can try the package from PyPi.

Sorry for the late response, I was caught up in few other activities. I have tested the wheels on linux aarch64 and it is working fine.

**Pull request merged**
