### PR TITLE
Implement elitism

### PR DESCRIPTION
**Pull request by leocus**
I implemented the possibility to add elitism in algorithms.eaSimple by using a new attribute of the toolbox ("replacement"), whose operators are defined in `tools/replacement.py`

### CODE REVIEW

**Comment by EyalWirsansky** [comment]
Any idea why this was not merged? was there any feedback?

**Comment by leocus** [comment]
Nope, no feedback at all

**Comment by EyalWirsansky** [comment]
> Nope, no feedback at all
If you would like to further discuss this issue between us, please connect with me on LinkedIn (just search for my name).

**Comment by leocus** [comment]
Can't message you, I sent you a connection request!

**Comment by fmder** [comment]
I'm not in favour of modifying the base algorithms. The modo of DEAP is to force users to open the box and implement their own algorithms (which I'm very happy you did!).

Small comment, in the replacement function you are comparing fitnesses to individuals.

**Pull request closed without merging**
