### PR TITLE
fix typo "dictionnary" -> "dictionary"

### PR DESCRIPTION
**Pull request by yxliang01**
All instances of the wrongly typed word "dictionnary" have been corrected by this PR.

### CODE REVIEW

**Comment by yxliang01** [comment]
The failed CI tasks have nothing to do with this PR. Restarting the failed jobs should be able to fix it.

**Comment by fmder** [comment]
The job should not have been launched automatically.

**Comment by yxliang01** [comment]
@fmder ? Is there anything actionable on my side?

**Comment by fmder** [comment]
No just a bad set up on my side :) thanks for your contribution

**Pull request merged**
