### PR TITLE
Harm

### PR DESCRIPTION
**Pull request by mgard**
Inclusion of HARM-GP in DEAP. As it is implemented as an algorithm, maybe the function should be called eaHarm instead of harm, but I'm not sure about it. Also added a simple example (still, it could be worthwhile to write a section in the documentation about this feature).

### CODE REVIEW

**Comment by fmder** [comment]
The gp.py will need the 
    
    # -*- coding: utf-8 -*-

**Comment by mgard** [comment]
Hum, weird, I tested it against Python 2.7 too... Instead of having the encoding of the whole file changed, I can also simply replace "Gagné" by "Gagne" in the HARM paper reference...

**Comment by fmder** [comment]
Can you please make the correction so that we can accept this unhoped-for contribution! Either changing "Gagné" to "Gagne" or adding an encoding will do.

**Comment by mgard** [comment]
Should by ok by now! (according to Travis at least...)

**Comment by fmder** [comment]
Next test is with the speed tests 55fa55dd

**Pull request merged**
