### PR TITLE
Replace calls to std. lib random with calls to numpy.random. Fixes #138

### LINKED ISSUE #138: Base Python's random module is inconsistent between Python 2 and 3
We've been using DEAP in [TPOT](https://github.com/rhiever/tpot), and have recently gotten bit by the fact that base Python's `random` module is inconsistent between Python 2 and 3. Minimal example:

```
Python 3.5.1 |Anaconda 2.4.0 (x86_64)| (default, Dec  7 2015, 11:24:55)
>>> import random
>>> random.seed(90)
>>> [random.randint(0, 100) for x in range(10)]
[26, 91, 11, 61, 84, 73, 75, 39, 81, 45]
```

```
Python 2.7.11 |Anaconda 2.5.0 (x86_64)| (default, Dec  6 2015, 18:57:58)
>>> import random
>>> random.seed(90)
>>> [random.randint(0, 100) for x in range(10)]
[20, 9, 66, 59, 64, 35, 45, 89, 82, 26]
```

I noticed that DEAP uses the base Python `random` module in some spots as well, e.g., [here](https://github.com/DEAP/deap/blob/af334219c168ed6c30403c587064a03f39d7d12a/deap/tools/mutation.py#L40)

I recommend using numpy's `random` module so the RNG is consistent between Python versions:

```
Python 3.5.1 |Anaconda 2.4.0 (x86_64)| (default, Dec  7 2015, 11:24:55)
>>> import numpy as np
>>> np.random.seed(90)
>>> np.random.randint(0, 90, 10)
array([29, 31, 67, 39, 68, 58, 37, 18, 74, 51])
>>> np.__version__
'1.11.0'
```

```
Python 2.7.11 |Anaconda 2.5.0 (x86_64)| (default, Dec  6 2015, 18:57:58)
>>> import numpy as np
>>> np.random.seed(90)
>>> np.random.randint(0, 90, 10)
array([29, 31, 67, 39, 68, 58, 37, 18, 74, 51])
>>> np.__version__
'1.11.0'
```

### PR DESCRIPTION
**Pull request by teaearlgraycold**
Okay so I'm not able to run the test suite locally because it seems like it's totally dependent on Python 2. Hoping Travis will tell me the current status of this build with this PR.

I went ahead and also replaced `print` statements with print functions (of course also adding `from __future__ import print_function`) to make the codebase more 3.X friendly.
#138

### CODE REVIEW

**Comment by fmder** [comment]
Thanks we'll look into it and prepare this PR for 2.0.

2016-06-02 15:12 GMT-04:00 Daniel <notifications@github.com>:

**Comment by fmder** [comment]
Can you check the error?

**Comment by teaearlgraycold** [comment]
@fmder, the CI build error? Yeah pretty sure that's because I'm using and writing for 3.X and you're only writing for 2.X.

>Thanks we'll look into it and prepare this PR for 2.0.

By this I thought you meant someone would take over this PR. I can try to set up a 2.X environment or something and try to get this fork to pass the CI if you want.

**Comment by fmder** [comment]
In the nsga2 an individual is completly replaced by an ndarray.
In gp it should be possible to have min = max to fix the tree size,

**Comment by teaearlgraycold** [comment]
I don't think I know enough about DEAP/numpy to fix all of the issues I'm seeing in Travis.

I did manage to fix the min/max issue easily enough, though.

**Comment by fmder** [comment]
I'll look into the ndarray type error,

Thanks :)

2016-06-20 22:00 GMT-04:00 Daniel <notifications@github.com>:

**Comment by fmder** [comment]
This has been merged in numpy-random branch.

**Pull request closed without merging**
